using DocxCore;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

string outputDir = @"C:\Users\Administrator\Documents\Github\Angri450.Nong\tests-output\05-docx";
string outputPath = Path.Combine(outputDir, "docx-basic.docx");

try
{
    Console.WriteLine("=== DocxCore Integration Test ===");
    Console.WriteLine();

    // All document creation happens in this block, which closes the file when done.
    {
        // Step 1: Create Word document
        Console.WriteLine("[1/5] Creating WordprocessingDocument...");
        using var doc = WordprocessingDocument.Create(outputPath, WordprocessingDocumentType.Document);
        var main = doc.AddMainDocumentPart();
        main.Document = new Document();
        var body = new Body();
        main.Document.Body = body;

        // Step 2: Add styles
        Console.WriteLine("[2/5] Building styles via StyleBuilder.BuildAll...");
        var stylesPart = main.AddNewPart<StyleDefinitionsPart>();
        stylesPart.Styles = new Styles();
        StyleBuilder.BuildAll(stylesPart.Styles);
        stylesPart.Styles.Save();

        // Step 3: Add numbering (for reference numbering)
        Console.WriteLine("[3/5] Building numbering via StyleBuilder.BuildNumbering...");
        var numPart = main.AddNewPart<NumberingDefinitionsPart>();
        numPart.Numbering = new Numbering();
        StyleBuilder.BuildNumbering(numPart.Numbering);
        numPart.Numbering.Save();

        // Step 4: Use DocumentWriter to build content
        Console.WriteLine("[4/5] Writing content with DocumentWriter...");
        var writer = new DocumentWriter(body, doc);

        // Title
        writer.Title("Test Document");

        // Subtitle
        writer.SubTitle("A Comprehensive Test of the DocxCore API");

        // Introduction
        writer.Heading("Introduction", 1);
        writer.Body("This test document was generated by the DocxCore library to verify that the ParagraphBuilder, TableBuilder, DocumentWriter, SectionBuilder, and StyleBuilder classes work correctly together. The library provides a fluent API for creating Word documents programmatically from .NET code.");

        // Features overview
        writer.Heading("Features Overview", 1);

        writer.Heading("ParagraphBuilder", 2);
        writer.Body("The ParagraphBuilder class provides a fluent interface for creating styled paragraphs. It supports text, bold text, superscript text, alignment, indentation, line spacing, and page break controls. Paragraphs can be composed by chaining method calls in a builder pattern.");

        // Demonstrate direct ParagraphBuilder usage (alongside DocumentWriter)
        Console.WriteLine("       Adding a direct ParagraphBuilder paragraph...");
        body.Append(new ParagraphBuilder()
            .Align(JustificationValues.Center)
            .Bold("Note: ")
            .Text("This paragraph was built directly with ParagraphBuilder and appended to the body, bypassing DocumentWriter.")
            .Build());

        writer.Heading("TableBuilder", 2);
        writer.Body("The TableBuilder class creates tables with customizable columns, header rows, data rows, border styles (including three-line academic table format), and Word built-in table styles. It uses a fluent API similar to ParagraphBuilder.");

        writer.Heading("DocumentWriter", 2);
        writer.Body("The DocumentWriter class provides a high-level API for building complete academic documents. It supports automatic heading numbering, reference detection in body text (e.g., [1]), footnotes, endnotes, cross-references, tables of contents, and more.");

        // Sample table using TableBuilder
        writer.Heading("Sample Data Table (TableBuilder)", 2);
        writer.Body("The following table was created using the TableBuilder class with three columns and three data rows. It demonstrates the fluent table-building API.");

        var table = new TableBuilder()
            .Columns(3000, 3000, 3000)
            .HeaderRow("Feature", "Class", "Status")
            .DataRow("Paragraph Rendering", "ParagraphBuilder", "PASS")
            .DataRow("Table Generation", "TableBuilder", "PASS")
            .DataRow("Style Definition", "StyleBuilder", "PASS")
            .Build();
        body.Append(table);
        body.Append(new Paragraph()); // spacing

        // Three-line academic table
        writer.Heading("Three-Line Academic Table (TableBuilder)", 2);
        writer.Body("The following table uses the ThreeLineBorders method to create a standard academic three-line table format.");

        var table2 = new TableBuilder()
            .Columns(2500, 2500, 2500, 2500)
            .ThreeLineBorders()
            .HeaderRow("Item", "Value A", "Value B", "Value C")
            .DataRow("Group 1", "10.5", "8.2", "12.1")
            .DataRow("Group 2", "9.3", "11.7", "7.8")
            .DataRow("Group 3", "14.2", "6.9", "10.4")
            .Build();
        body.Append(table2);
        body.Append(new Paragraph());

        // Footnote test
        writer.Heading("Footnotes and Endnotes", 2);
        writer.Body("This paragraph demonstrates footnote functionality");
        writer.Footnote("This is a footnote generated by DocumentWriter.Footnote. It provides supplementary information at the bottom of the page.");
        writer.Body(" and this sentence is followed by an endnote");
        writer.Endnote("This is an endnote generated by DocumentWriter.Endnote. Endnotes appear at the end of the document rather than at the bottom of the page.");
        writer.Body(". The references [1] should be automatically detected and formatted as superscript.");

        // Cross reference
        writer.Heading("Cross References", 2);
        writer.Body("Cross references allow linking to bookmarked locations within the document. For example, ");
        writer.Bookmark("_RefSection");
        writer.CrossReference("_RefSection", "see this bookmarked section");
        writer.Body(" demonstrates cross-reference functionality.");

        // References
        writer.Heading("References", 1);
        writer.BibHeading("References");
        writer.References(
            "[1] Smith, J. (2024). Document Generation Techniques for Scientific Computing. Journal of Software Engineering, 15(3), 123-145.",
            "[2] Zhang, L. (2023). OpenXML Programming Guide: From Basics to Advanced Topics. Beijing: Tsinghua University Press.",
            "[3] Li, W. and Chen, X. (2025). Modern Document Processing with .NET and OpenXML. Shanghai: Science Press.");

        // Page layout with SectionBuilder
        Console.WriteLine("[5/5] Applying page layout via SectionBuilder...");
        var sectPr = new SectionBuilder()
            .A4()
            .Margins("2.5cm", "2.5cm", "3cm", "2.5cm")
            .Build();
        body.Append(sectPr);

        main.Document.Save();
    } // using block ends here, file is flushed and closed

    // Verify output (after the file is fully flushed to disk)
    var fi = new FileInfo(outputPath);
    if (!fi.Exists)
    {
        Console.WriteLine("FAIL: Output file was not created.");
        Environment.Exit(1);
    }

    Console.WriteLine();
    Console.WriteLine("=== Results ===");
    Console.WriteLine($"  Output file : {outputPath}");
    Console.WriteLine($"  File size   : {fi.Length:N0} bytes");
    Console.WriteLine($"  File exists : YES");
    Console.WriteLine();
    Console.WriteLine("PASS: Document created and saved successfully.");
    Console.WriteLine("All API components tested: ParagraphBuilder, TableBuilder, DocumentWriter,");
    Console.WriteLine("  SectionBuilder, StyleBuilder, StyleBuilder.BuildNumbering.");
    Console.WriteLine("Features tested: titles, subtitles, headings (H1/H2), body text,");
    Console.WriteLine("  bold/superscript formatting, tables, three-line tables, footnotes,");
    Console.WriteLine("  endnotes, cross-references, bookmarks, and references.");
}
catch (Exception ex)
{
    Console.WriteLine();
    Console.WriteLine($"FAIL: {ex.GetType().Name}: {ex.Message}");
    Console.WriteLine(ex.StackTrace);
    Environment.Exit(1);
}
